### ISSUE TITLE
Repository cleanup and refactoring name space

### ISSUE THREAD

**Issue by ojgarciab** [JdeRobot4Android/AndroidCameraViewer#1]
There is a namespace called com.example... that could be org.jderobot.androidcameraviewer, I'll change this in cameraserver too.

There is some MacOS temporary files that could be removed, so I'll create a new .gitignore to avoid upload them.

**Comment by gsssrao** [comment]
Thanks!!

**Comment by ojgarciab** [comment]
You're welcome! :)
