### ISSUE TITLE
Show fps and bandwidth usage

### ISSUE THREAD

**Issue by ojgarciab** [JdeRobot4Android/AndroidCameraViewer#12]
There could be a good idea show fps and bandwidth usage.

**Comment by gsssrao** [comment]
Have you already done this? If not then I would also like to do. I had classes in the morning so could not do it then.

**Comment by gsssrao** [comment]
You did not reply so I completed this.

**Comment by ojgarciab** [comment]
Sorry I was busy. I'll open a new issue to avoid calculating bytes with pixel format, width and height.
