### ISSUE TITLE
Calculate fps and bandwidth smoothly as 2 seconds average

### ISSUE THREAD

**Issue by ojgarciab** [JdeRobot4Android/AndroidCameraViewer#18]
I'll implement a average fps based on frames received last 2 seconds, but updating data every frame, so fps and bandwidth will be more accurate when slow frame rates (< 3 fps) are a problem.

**Comment by ojgarciab** [comment]
It's much more smooth with 3 seconds average.

Displayed fps and bandwidth data is updated at most 2 times per second.

Check the update and merge when you have review the code.

**Comment by gsssrao** [comment]
Great!! I will merge it now. After this I will have to leave , I have an exam. I fixed #16 as well.

**Comment by ojgarciab** [comment]
You're welcome, and good luck!
